---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: enterprise-search-python
spec:
  type: library
  owner: group:devtools-team
  lifecycle: production

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: enterprise-search-python-test
  description: Test enterprise-search-python client
spec:
  type: buildkite-pipeline
  owner: group:devtools-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: enterprise-search-python-test
    spec:
      repository: elastic/enterprise-search-python
      pipeline_file: .buildkite/pipeline.yml
      teams:
        devtools-team:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
      provider_settings:
        build_pull_requests: true
        build_branches: true
      cancel_intermediate_builds: true
      cancel_intermediate_builds_branch_filter: '!main'
