---
steps:
  - label: ":python: {{ matrix.python }} :elastic-enterprise-search: {{ matrix.stack_version }}"
    agents:
      provider: gcp
    matrix:
      setup:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        stack_version:
          - "8.11.0-SNAPSHOT"
    env:
      PYTHON_VERSION: "{{ matrix.python }}"
      STACK_VERSION: "{{ matrix.stack_version }}"
    command: ./.buildkite/run-tests