#!/usr/bin/env bash
#
# Version 1.1
# - Moved to .buildkite folder and separated out `run-repository.sh`
# - Add `$RUNSCRIPTS` env var for running Elasticsearch dependent products

# Default environment variables
export PYTHON_VERSION=${PYTHON_VERSION-3.9}
export RUNSCRIPTS=enterprise-search
export TEST_SUITE=platinum

script_path=$(dirname $(realpath -s $0))
source $script_path/functions/imports.sh
set -euo pipefail

echo "--- :python: :elastic-enterprise-search: Start $STACK_VERSION container"
DETACH=true bash .buildkite/run-elasticsearch.sh

if [[ -n "$RUNSCRIPTS" ]]; then
  for RUNSCRIPT in ${RUNSCRIPTS//,/ } ; do
    echo -e "--- Running run-$RUNSCRIPT.sh"
    CONTAINER_NAME=${RUNSCRIPT} \
      DETACH=true \
      bash .buildkite/run-${RUNSCRIPT}.sh
  done
fi

echo -e "--- Run repository specific tests"
bash .buildkite/run-repository.sh
